// ============================================================
// data.js — Base de datos de los 118 elementos de la tabla periódica
// Incluye: símbolo, nombre (ES/EN), número atómico, electronegatividad,
// categoría, grupo, período y color de tarjeta.
// ============================================================

window.ELEMENTS = [
  // Z, symbol, name_es, name_en, electronegativity (Pauling), category, group, period
  { z:1,  sym:"H",  es:"Hidrógeno",    en:"Hydrogen",      en_val:2.20, cat:"nonmetal",        grp:1,   per:1 },
  { z:2,  sym:"He", es:"Helio",        en:"Helium",        en_val:null, cat:"noble_gas",        grp:18,  per:1 },
  { z:3,  sym:"Li", es:"Litio",        en:"Lithium",       en_val:0.98, cat:"alkali_metal",     grp:1,   per:2 },
  { z:4,  sym:"Be", es:"Berilio",      en:"Beryllium",     en_val:1.57, cat:"alkaline_earth",   grp:2,   per:2 },
  { z:5,  sym:"B",  es:"Boro",         en:"Boron",         en_val:2.04, cat:"metalloid",        grp:13,  per:2 },
  { z:6,  sym:"C",  es:"Carbono",      en:"Carbon",        en_val:2.55, cat:"nonmetal",         grp:14,  per:2 },
  { z:7,  sym:"N",  es:"Nitrógeno",    en:"Nitrogen",      en_val:3.04, cat:"nonmetal",         grp:15,  per:2 },
  { z:8,  sym:"O",  es:"Oxígeno",      en:"Oxygen",        en_val:3.44, cat:"nonmetal",         grp:16,  per:2 },
  { z:9,  sym:"F",  es:"Flúor",        en:"Fluorine",      en_val:3.98, cat:"halogen",          grp:17,  per:2 },
  { z:10, sym:"Ne", es:"Neón",         en:"Neon",          en_val:null, cat:"noble_gas",        grp:18,  per:2 },
  { z:11, sym:"Na", es:"Sodio",        en:"Sodium",        en_val:0.93, cat:"alkali_metal",     grp:1,   per:3 },
  { z:12, sym:"Mg", es:"Magnesio",     en:"Magnesium",     en_val:1.31, cat:"alkaline_earth",   grp:2,   per:3 },
  { z:13, sym:"Al", es:"Aluminio",     en:"Aluminum",      en_val:1.61, cat:"post_transition",  grp:13,  per:3 },
  { z:14, sym:"Si", es:"Silicio",      en:"Silicon",       en_val:1.90, cat:"metalloid",        grp:14,  per:3 },
  { z:15, sym:"P",  es:"Fósforo",      en:"Phosphorus",    en_val:2.19, cat:"nonmetal",         grp:15,  per:3 },
  { z:16, sym:"S",  es:"Azufre",       en:"Sulfur",        en_val:2.58, cat:"nonmetal",         grp:16,  per:3 },
  { z:17, sym:"Cl", es:"Cloro",        en:"Chlorine",      en_val:3.16, cat:"halogen",          grp:17,  per:3 },
  { z:18, sym:"Ar", es:"Argón",        en:"Argon",         en_val:null, cat:"noble_gas",        grp:18,  per:3 },
  { z:19, sym:"K",  es:"Potasio",      en:"Potassium",     en_val:0.82, cat:"alkali_metal",     grp:1,   per:4 },
  { z:20, sym:"Ca", es:"Calcio",       en:"Calcium",       en_val:1.00, cat:"alkaline_earth",   grp:2,   per:4 },
  { z:21, sym:"Sc", es:"Escandio",     en:"Scandium",      en_val:1.36, cat:"transition_metal", grp:3,   per:4 },
  { z:22, sym:"Ti", es:"Titanio",      en:"Titanium",      en_val:1.54, cat:"transition_metal", grp:4,   per:4 },
  { z:23, sym:"V",  es:"Vanadio",      en:"Vanadium",      en_val:1.63, cat:"transition_metal", grp:5,   per:4 },
  { z:24, sym:"Cr", es:"Cromo",        en:"Chromium",      en_val:1.66, cat:"transition_metal", grp:6,   per:4 },
  { z:25, sym:"Mn", es:"Manganeso",    en:"Manganese",     en_val:1.55, cat:"transition_metal", grp:7,   per:4 },
  { z:26, sym:"Fe", es:"Hierro",       en:"Iron",          en_val:1.83, cat:"transition_metal", grp:8,   per:4 },
  { z:27, sym:"Co", es:"Cobalto",      en:"Cobalt",        en_val:1.88, cat:"transition_metal", grp:9,   per:4 },
  { z:28, sym:"Ni", es:"Níquel",       en:"Nickel",        en_val:1.91, cat:"transition_metal", grp:10,  per:4 },
  { z:29, sym:"Cu", es:"Cobre",        en:"Copper",        en_val:1.90, cat:"transition_metal", grp:11,  per:4 },
  { z:30, sym:"Zn", es:"Zinc",         en:"Zinc",          en_val:1.65, cat:"transition_metal", grp:12,  per:4 },
  { z:31, sym:"Ga", es:"Galio",        en:"Gallium",       en_val:1.81, cat:"post_transition",  grp:13,  per:4 },
  { z:32, sym:"Ge", es:"Germanio",     en:"Germanium",     en_val:2.01, cat:"metalloid",        grp:14,  per:4 },
  { z:33, sym:"As", es:"Arsénico",     en:"Arsenic",       en_val:2.18, cat:"metalloid",        grp:15,  per:4 },
  { z:34, sym:"Se", es:"Selenio",      en:"Selenium",      en_val:2.55, cat:"nonmetal",         grp:16,  per:4 },
  { z:35, sym:"Br", es:"Bromo",        en:"Bromine",       en_val:2.96, cat:"halogen",          grp:17,  per:4 },
  { z:36, sym:"Kr", es:"Kriptón",      en:"Krypton",       en_val:null, cat:"noble_gas",        grp:18,  per:4 },
  { z:37, sym:"Rb", es:"Rubidio",      en:"Rubidium",      en_val:0.82, cat:"alkali_metal",     grp:1,   per:5 },
  { z:38, sym:"Sr", es:"Estroncio",    en:"Strontium",     en_val:0.95, cat:"alkaline_earth",   grp:2,   per:5 },
  { z:39, sym:"Y",  es:"Itrio",        en:"Yttrium",       en_val:1.22, cat:"transition_metal", grp:3,   per:5 },
  { z:40, sym:"Zr", es:"Circonio",     en:"Zirconium",     en_val:1.33, cat:"transition_metal", grp:4,   per:5 },
  { z:41, sym:"Nb", es:"Niobio",       en:"Niobium",       en_val:1.60, cat:"transition_metal", grp:5,   per:5 },
  { z:42, sym:"Mo", es:"Molibdeno",    en:"Molybdenum",    en_val:2.16, cat:"transition_metal", grp:6,   per:5 },
  { z:43, sym:"Tc", es:"Tecnecio",     en:"Technetium",    en_val:1.90, cat:"transition_metal", grp:7,   per:5 },
  { z:44, sym:"Ru", es:"Rutenio",      en:"Ruthenium",     en_val:2.20, cat:"transition_metal", grp:8,   per:5 },
  { z:45, sym:"Rh", es:"Rodio",        en:"Rhodium",       en_val:2.28, cat:"transition_metal", grp:9,   per:5 },
  { z:46, sym:"Pd", es:"Paladio",      en:"Palladium",     en_val:2.20, cat:"transition_metal", grp:10,  per:5 },
  { z:47, sym:"Ag", es:"Plata",        en:"Silver",        en_val:1.93, cat:"transition_metal", grp:11,  per:5 },
  { z:48, sym:"Cd", es:"Cadmio",       en:"Cadmium",       en_val:1.69, cat:"transition_metal", grp:12,  per:5 },
  { z:49, sym:"In", es:"Indio",        en:"Indium",        en_val:1.78, cat:"post_transition",  grp:13,  per:5 },
  { z:50, sym:"Sn", es:"Estaño",       en:"Tin",           en_val:1.96, cat:"post_transition",  grp:14,  per:5 },
  { z:51, sym:"Sb", es:"Antimonio",    en:"Antimony",      en_val:2.05, cat:"metalloid",        grp:15,  per:5 },
  { z:52, sym:"Te", es:"Teluro",       en:"Tellurium",     en_val:2.10, cat:"metalloid",        grp:16,  per:5 },
  { z:53, sym:"I",  es:"Yodo",         en:"Iodine",        en_val:2.66, cat:"halogen",          grp:17,  per:5 },
  { z:54, sym:"Xe", es:"Xenón",        en:"Xenon",         en_val:null, cat:"noble_gas",        grp:18,  per:5 },
  { z:55, sym:"Cs", es:"Cesio",        en:"Cesium",        en_val:0.79, cat:"alkali_metal",     grp:1,   per:6 },
  { z:56, sym:"Ba", es:"Bario",        en:"Barium",        en_val:0.89, cat:"alkaline_earth",   grp:2,   per:6 },
  { z:57, sym:"La", es:"Lantano",      en:"Lanthanum",     en_val:1.10, cat:"lanthanide",       grp:3,   per:6 },
  { z:58, sym:"Ce", es:"Cerio",        en:"Cerium",        en_val:1.12, cat:"lanthanide",       grp:3,   per:6 },
  { z:59, sym:"Pr", es:"Praseodimio",  en:"Praseodymium",  en_val:1.13, cat:"lanthanide",       grp:3,   per:6 },
  { z:60, sym:"Nd", es:"Neodimio",     en:"Neodymium",     en_val:1.14, cat:"lanthanide",       grp:3,   per:6 },
  { z:61, sym:"Pm", es:"Prometio",     en:"Promethium",    en_val:1.13, cat:"lanthanide",       grp:3,   per:6 },
  { z:62, sym:"Sm", es:"Samario",      en:"Samarium",      en_val:1.17, cat:"lanthanide",       grp:3,   per:6 },
  { z:63, sym:"Eu", es:"Europio",      en:"Europium",      en_val:1.20, cat:"lanthanide",       grp:3,   per:6 },
  { z:64, sym:"Gd", es:"Gadolinio",    en:"Gadolinium",    en_val:1.20, cat:"lanthanide",       grp:3,   per:6 },
  { z:65, sym:"Tb", es:"Terbio",       en:"Terbium",       en_val:1.10, cat:"lanthanide",       grp:3,   per:6 },
  { z:66, sym:"Dy", es:"Disprosio",    en:"Dysprosium",    en_val:1.22, cat:"lanthanide",       grp:3,   per:6 },
  { z:67, sym:"Ho", es:"Holmio",       en:"Holmium",       en_val:1.23, cat:"lanthanide",       grp:3,   per:6 },
  { z:68, sym:"Er", es:"Erbio",        en:"Erbium",        en_val:1.24, cat:"lanthanide",       grp:3,   per:6 },
  { z:69, sym:"Tm", es:"Tulio",        en:"Thulium",       en_val:1.25, cat:"lanthanide",       grp:3,   per:6 },
  { z:70, sym:"Yb", es:"Iterbio",      en:"Ytterbium",     en_val:1.10, cat:"lanthanide",       grp:3,   per:6 },
  { z:71, sym:"Lu", es:"Lutecio",      en:"Lutetium",      en_val:1.27, cat:"lanthanide",       grp:3,   per:6 },
  { z:72, sym:"Hf", es:"Hafnio",       en:"Hafnium",       en_val:1.30, cat:"transition_metal", grp:4,   per:6 },
  { z:73, sym:"Ta", es:"Tantalio",     en:"Tantalum",      en_val:1.50, cat:"transition_metal", grp:5,   per:6 },
  { z:74, sym:"W",  es:"Wolframio",    en:"Tungsten",      en_val:2.36, cat:"transition_metal", grp:6,   per:6 },
  { z:75, sym:"Re", es:"Renio",        en:"Rhenium",       en_val:1.90, cat:"transition_metal", grp:7,   per:6 },
  { z:76, sym:"Os", es:"Osmio",        en:"Osmium",        en_val:2.20, cat:"transition_metal", grp:8,   per:6 },
  { z:77, sym:"Ir", es:"Iridio",       en:"Iridium",       en_val:2.20, cat:"transition_metal", grp:9,   per:6 },
  { z:78, sym:"Pt", es:"Platino",      en:"Platinum",      en_val:2.28, cat:"transition_metal", grp:10,  per:6 },
  { z:79, sym:"Au", es:"Oro",          en:"Gold",          en_val:2.54, cat:"transition_metal", grp:11,  per:6 },
  { z:80, sym:"Hg", es:"Mercurio",     en:"Mercury",       en_val:2.00, cat:"transition_metal", grp:12,  per:6 },
  { z:81, sym:"Tl", es:"Talio",        en:"Thallium",      en_val:1.62, cat:"post_transition",  grp:13,  per:6 },
  { z:82, sym:"Pb", es:"Plomo",        en:"Lead",          en_val:2.33, cat:"post_transition",  grp:14,  per:6 },
  { z:83, sym:"Bi", es:"Bismuto",      en:"Bismuth",       en_val:2.02, cat:"post_transition",  grp:15,  per:6 },
  { z:84, sym:"Po", es:"Polonio",      en:"Polonium",      en_val:2.00, cat:"metalloid",        grp:16,  per:6 },
  { z:85, sym:"At", es:"Astato",       en:"Astatine",      en_val:2.20, cat:"halogen",          grp:17,  per:6 },
  { z:86, sym:"Rn", es:"Radón",        en:"Radon",         en_val:null, cat:"noble_gas",        grp:18,  per:6 },
  { z:87, sym:"Fr", es:"Francio",      en:"Francium",      en_val:0.70, cat:"alkali_metal",     grp:1,   per:7 },
  { z:88, sym:"Ra", es:"Radio",        en:"Radium",        en_val:0.90, cat:"alkaline_earth",   grp:2,   per:7 },
  { z:89, sym:"Ac", es:"Actinio",      en:"Actinium",      en_val:1.10, cat:"actinide",         grp:3,   per:7 },
  { z:90, sym:"Th", es:"Torio",        en:"Thorium",       en_val:1.30, cat:"actinide",         grp:3,   per:7 },
  { z:91, sym:"Pa", es:"Protactinio",  en:"Protactinium",  en_val:1.50, cat:"actinide",         grp:3,   per:7 },
  { z:92, sym:"U",  es:"Uranio",       en:"Uranium",       en_val:1.38, cat:"actinide",         grp:3,   per:7 },
  { z:93, sym:"Np", es:"Neptunio",     en:"Neptunium",     en_val:1.36, cat:"actinide",         grp:3,   per:7 },
  { z:94, sym:"Pu", es:"Plutonio",     en:"Plutonium",     en_val:1.28, cat:"actinide",         grp:3,   per:7 },
  { z:95, sym:"Am", es:"Americio",     en:"Americium",     en_val:1.13, cat:"actinide",         grp:3,   per:7 },
  { z:96, sym:"Cm", es:"Curio",        en:"Curium",        en_val:1.28, cat:"actinide",         grp:3,   per:7 },
  { z:97, sym:"Bk", es:"Berkelio",     en:"Berkelium",     en_val:1.30, cat:"actinide",         grp:3,   per:7 },
  { z:98, sym:"Cf", es:"Californio",   en:"Californium",   en_val:1.30, cat:"actinide",         grp:3,   per:7 },
  { z:99, sym:"Es", es:"Einstenio",    en:"Einsteinium",   en_val:1.30, cat:"actinide",         grp:3,   per:7 },
  { z:100,sym:"Fm", es:"Fermio",       en:"Fermium",       en_val:1.30, cat:"actinide",         grp:3,   per:7 },
  { z:101,sym:"Md", es:"Mendelevio",   en:"Mendelevium",   en_val:1.30, cat:"actinide",         grp:3,   per:7 },
  { z:102,sym:"No", es:"Nobelio",      en:"Nobelium",      en_val:1.30, cat:"actinide",         grp:3,   per:7 },
  { z:103,sym:"Lr", es:"Lawrencio",    en:"Lawrencium",    en_val:1.30, cat:"actinide",         grp:3,   per:7 },
  { z:104,sym:"Rf", es:"Rutherfordio", en:"Rutherfordium", en_val:null, cat:"transition_metal", grp:4,   per:7 },
  { z:105,sym:"Db", es:"Dubnio",       en:"Dubnium",       en_val:null, cat:"transition_metal", grp:5,   per:7 },
  { z:106,sym:"Sg", es:"Seaborgio",    en:"Seaborgium",    en_val:null, cat:"transition_metal", grp:6,   per:7 },
  { z:107,sym:"Bh", es:"Bohrio",       en:"Bohrium",       en_val:null, cat:"transition_metal", grp:7,   per:7 },
  { z:108,sym:"Hs", es:"Hasio",        en:"Hassium",       en_val:null, cat:"transition_metal", grp:8,   per:7 },
  { z:109,sym:"Mt", es:"Meitnerio",    en:"Meitnerium",    en_val:null, cat:"transition_metal", grp:9,   per:7 },
  { z:110,sym:"Ds", es:"Darmstadio",   en:"Darmstadtium",  en_val:null, cat:"transition_metal", grp:10,  per:7 },
  { z:111,sym:"Rg", es:"Roentgenio",   en:"Roentgenium",   en_val:null, cat:"transition_metal", grp:11,  per:7 },
  { z:112,sym:"Cn", es:"Copernicio",   en:"Copernicium",   en_val:null, cat:"transition_metal", grp:12,  per:7 },
  { z:113,sym:"Nh", es:"Nihonio",      en:"Nihonium",      en_val:null, cat:"post_transition",  grp:13,  per:7 },
  { z:114,sym:"Fl", es:"Flerovio",     en:"Flerovium",     en_val:null, cat:"post_transition",  grp:14,  per:7 },
  { z:115,sym:"Mc", es:"Moscovio",     en:"Moscovium",     en_val:null, cat:"post_transition",  grp:15,  per:7 },
  { z:116,sym:"Lv", es:"Livermorio",   en:"Livermorium",   en_val:null, cat:"post_transition",  grp:16,  per:7 },
  { z:117,sym:"Ts", es:"Teneso",       en:"Tennessine",    en_val:null, cat:"halogen",          grp:17,  per:7 },
  { z:118,sym:"Og", es:"Oganesón",     en:"Oganesson",     en_val:null, cat:"noble_gas",        grp:18,  per:7 },
];

// Category metadata
window.CAT_META = {
  alkali_metal:     { label:"Metal Alcalino",        isMetal: true,  isNonMetal: false, isSemi: false, color1:"#1c0a3a", color2:"#0d0520" },
  alkaline_earth:   { label:"Metal Alcalinotérreo",  isMetal: true,  isNonMetal: false, isSemi: false, color1:"#1a2a0a", color2:"#0d1405" },
  transition_metal: { label:"Metal de Transición",   isMetal: true,  isNonMetal: false, isSemi: false, color1:"#0a1a2a", color2:"#050d14" },
  post_transition:  { label:"Metal Post-Transición", isMetal: true,  isNonMetal: false, isSemi: false, color1:"#0a1620", color2:"#050b10" },
  metalloid:        { label:"Semimetal",              isMetal: false, isNonMetal: false, isSemi: true,  color1:"#1a0a2a", color2:"#0d0515" },
  nonmetal:         { label:"No Metal",               isMetal: false, isNonMetal: true,  isSemi: false, color1:"#0a2a1a", color2:"#051410" },
  halogen:          { label:"Halógeno",               isMetal: false, isNonMetal: true,  isSemi: false, color1:"#2a0a1a", color2:"#14050d" },
  noble_gas:        { label:"Gas Noble",              isMetal: false, isNonMetal: true,  isSemi: false, color1:"#0a0a2a", color2:"#050514" },
  lanthanide:       { label:"Lantánido",              isMetal: true,  isNonMetal: false, isSemi: false, color1:"#1a1a0a", color2:"#0d0d05" },
  actinide:         { label:"Actínido",               isMetal: true,  isNonMetal: false, isSemi: false, color1:"#2a1a0a", color2:"#140d05" },
};
